version: '3'

services:
  app:
    image: affiliate-tracker:v1
    container_name: ${APP_NAME}
    volumes:
      - .:/app
    ports:
      - ${APP_PORT_HOST}:${APP_PORT_CONTAINER}
  db:
    image: postgres:14.4-alpine
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ./db/docker/db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    container_name: ${PGADMIN_CONTAINER_NAME}
    ports:
      - ${PGADMIN_PORT_HOST}:${PGADMIN_PORT_CONTAINER}
    volumes:
      - ./db/docker/pgadmin-data:/var/lib/postgresql/data
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
